import { Sparkles } from 'lucide-react'

export interface AIDisclaimerProps {
  variant?: 'full' | 'compact' | 'inline'
  className?: string
  model?: string
}

/**
 * AI Content Attribution Component
 * 2026 UX Standards: Calm, trustworthy, informative
 * Shows AI attribution with model info and context
 */
export default function AIDisclaimer({
  variant = 'full',
  className = '',
  model = 'Claude'
}: AIDisclaimerProps) {
  // Inline variant - minimal, for use next to AI-generated text
  if (variant === 'inline') {
    return (
      <span className={`inline-flex items-center gap-1 text-xs text-neutral-500 ${className}`}>
        <Sparkles className="h-3 w-3 text-primary-500" />
        <span>AI</span>
      </span>
    )
  }

  // Compact variant - single line with icon
  if (variant === 'compact') {
    return (
      <div className={`flex items-center gap-2 text-sm text-neutral-600 ${className}`}>
        <Sparkles className="h-4 w-4 text-primary-500" />
        <span>AI-generated by {model} · Review for accuracy</span>
      </div>
    )
  }

  // Full variant - detailed with context
  return (
    <div className={`bg-primary-50 border border-primary-100 rounded-lg p-4 ${className}`}>
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0 mt-0.5">
          <Sparkles className="h-5 w-5 text-primary-600" />
        </div>
        <div className="flex-1">
          <h3 className="text-sm font-semibold text-neutral-900 mb-1 flex items-center gap-2">
            AI-Generated Content
            <span className="text-xs font-normal text-neutral-500 bg-white px-2 py-0.5 rounded-full">
              {model}
            </span>
          </h3>
          <p className="text-sm text-neutral-600 leading-relaxed">
            This content was created by AI and should be reviewed for accuracy.
            Verify important facts before using in professional contexts.
          </p>
        </div>
      </div>
    </div>
  )
}
