import React from 'react'
import { Sparkles, AlertTriangle } from 'lucide-react'

export interface AIDisclaimerProps {
  variant?: 'full' | 'compact' | 'inline' | 'warning'
  className?: string
  model?: string
}

/**
 * AI Content Attribution Component
 *
 * CLAUDE.md compliant AI-generated content disclaimer.
 * Required for all AI-generated content per CLAUDE.md Section 4.
 *
 * Variants:
 * - full: Detailed disclaimer with model info (use for primary AI content)
 * - warning: Prominent yellow warning for critical AI content requiring verification
 * - compact: Single line with icon (use for secondary AI content)
 * - inline: Minimal indicator (use inline with text)
 *
 * @example
 * // For synthesis reports, summaries (critical content)
 * <AIDisclaimer variant="warning" />
 *
 * @example
 * // For AI suggestions, recommendations
 * <AIDisclaimer variant="full" model="Claude" />
 */
export default function AIDisclaimer({
  variant = 'full',
  className = '',
  model = 'Claude'
}: AIDisclaimerProps): React.JSX.Element {
  // Inline variant - minimal, for use next to AI-generated text
  if (variant === 'inline') {
    return (
      <span
        className={`inline-flex items-center gap-1 text-xs text-neutral-500 ${className}`}
        role="note"
        aria-label="AI-generated content"
      >
        <Sparkles className="h-3 w-3 text-primary-500" aria-hidden="true" />
        <span>AI</span>
      </span>
    )
  }

  // Compact variant - single line with icon
  if (variant === 'compact') {
    return (
      <div
        className={`flex items-center gap-2 text-sm text-neutral-600 ${className}`}
        role="note"
        aria-label={`AI-generated by ${model}`}
      >
        <Sparkles className="h-4 w-4 text-primary-500" aria-hidden="true" />
        <span>AI-generated by {model} · Review for accuracy</span>
      </div>
    )
  }

  // Warning variant - prominent disclaimer for critical content (CLAUDE.md compliant)
  if (variant === 'warning') {
    return (
      <div
        className={`bg-yellow-50 border border-yellow-200 rounded-lg p-4 ${className}`}
        role="alert"
        aria-live="polite"
      >
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0 mt-0.5">
            <AlertTriangle className="h-5 w-5 text-yellow-600" aria-hidden="true" />
          </div>
          <div className="flex-1">
            <h3 className="text-sm font-semibold text-yellow-900 mb-1">
              ⚠️ AI-Generated Content
            </h3>
            <p className="text-sm text-yellow-800 leading-relaxed">
              This content is created by AI and should be reviewed for accuracy.
              Verify important facts and citations before using in academic or professional contexts.
            </p>
          </div>
        </div>
      </div>
    )
  }

  // Full variant - detailed with context
  return (
    <div
      className={`bg-primary-50 border border-primary-100 rounded-lg p-4 ${className}`}
      role="note"
      aria-label={`Content generated by ${model} AI`}
    >
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0 mt-0.5">
          <Sparkles className="h-5 w-5 text-primary-600" aria-hidden="true" />
        </div>
        <div className="flex-1">
          <h3 className="text-sm font-semibold text-neutral-900 mb-1 flex items-center gap-2">
            AI-Generated Content
            <span className="text-xs font-normal text-neutral-500 bg-white px-2 py-0.5 rounded-full">
              {model}
            </span>
          </h3>
          <p className="text-sm text-neutral-600 leading-relaxed">
            This content was created by AI and should be reviewed for accuracy.
            Verify important facts before using in professional contexts.
          </p>
        </div>
      </div>
    </div>
  )
}
